
import property
import sys
import time
import translator

def main():
#    file_path1 = 'english.prop' # English
#    file_path2 = 'chinese.prop' # Chinese
    file_path1 = sys.argv[1]
    file_path2 = sys.argv[2]
    props1 = property.parse(file_path1)
    props2 = property.parse(file_path2)
#    print(props1.properties)
#    print(props2.properties)
    keys_not_in_chinese = []
    for key1 in props1.properties.keys():
        has_chinese_key = False
        for key2 in props2.properties.keys():
#            print("{}, {}".format(key1, key2))
            if key1 == key2:
                has_chinese_key = True
                break
        if not has_chinese_key:
            keys_not_in_chinese.append(key1)
    keys_not_in_chinese = sorted(keys_not_in_chinese)
    print(keys_not_in_chinese)
    print("Found {} keys different".format(len(keys_not_in_chinese)))
    current_time = time.time()
    diff_props_file_content = "# Generated by Translation Diff Generator\n#\n# Date: {}\n# English translation count: {}\n# Chinese translation count: {}\n# Diff count: {}\n#\n\n"\
            .format(time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(current_time)), len(props1.properties), len(props2.properties), len(keys_not_in_chinese))
    zh_diff_props_file_content = diff_props_file_content
    for key in keys_not_in_chinese:
        value = props1.get(key)
        spider = translator.BaiduTranslator(value)
        print("Translating: {}".format(value))
        zh_value = spider.run()
        print("Translated: {}".format(zh_value))
        diff_props_file_content += key
        diff_props_file_content += '='
        diff_props_file_content += value
        diff_props_file_content += '\n'
        zh_diff_props_file_content += key
        zh_diff_props_file_content += '='
        zh_diff_props_file_content += zh_value
        zh_diff_props_file_content += '\n'
    diff_props_file = open("diff.prop", "w")
    diff_props_file.write(diff_props_file_content)
    diff_props_file.close()
    zh_diff_props_file = open("zh_diff.prop", "w")
    zh_diff_props_file.write(zh_diff_props_file_content)
    zh_diff_props_file.close()

if __name__ == '__main__':
    main()
